### ISSUE TITLE
Spring cleaning of 2015

### ISSUE THREAD

**Issue by Stanzilla** [kvirc/kvirc-www#5]
I agree that stuff has to be condensed some more, let's just start collecting stuff here?
- [ ] Everything under `running kvirc` should just be one, big, download page and also have `Download` as the name.
- [ ] The two FAQs should be merged (one GitHub page or one on the site itself?)
- [x] http://kvirc.net/?id=status&lang=en super outdated info, most of it useless, too. Remove or link to https://github.com/kvirc/KVIrc/graphs/contributors? modedit **Was updated instead**
- [ ] http://kvirc.net/?id=features&lang=en Probably outdated info, remove "personal" comments? 
- [ ] http://kvirc.net/?id=license&lang=en Remove, it's on the GitHub repo anyway.
- [ ] http://kvirc.net/?id=honor&lang=en could use a link to `https://github.com/kvirc/KVIrc/graphs/contributors` at the top
-  KVirc related
  - [x] http://kvirc.fr/ seems dead
  - [x] http://kvircfr.les-forums.com/forums/ more than dead, just spam posts there
  - [x] http://kvirc.dotadata.de/ also dead
-  Graphic suite
  - [ ] http://kvirc.net/?id=banners&lang=en eh, drop it imo. That's more 90's than anything else :smile: 
  - [ ] http://kvirc.net/?id=arts&lang=en same as above
-  Misc
  - [ ] http://kvirc.net/?id=changelog&lang=en drop it, out of date anyway and the Download page should probably handle that and/or link to the git log for nightlies
  - [ ] http://kvirc.net/?id=addons&lang=en drop it, there is no content there
  - [x] http://kvirc.net/?id=scripts&lang=en SVN -> Git, update text, does that stuff even work anymore with the latest version of KVirc?
  - [x] http://kvirc.net/?id=translation&lang=en GIT -> Git  
    --modedit--
  - [x] Remove broken oldsite
  - [x] Fix menu entries
  - [x] Remove broken mirrors

**Comment by un1versal** [comment]
The Downloads page and content is outdated, severely wrong and unstable builds offered, in Windows they all crash badly, IMO the appveyor builds are more stable than any of those.

Also d00p builds dont support audio events last I checked, good thing I dont use Windows my self compile is hanging on and now waiting for Master to build again as currently fails compile.

**Comment by un1versal** [comment]
It would be nice if the content of those pages would be available in git. You cant very well have community driven updates to those if that's not happening or if you waiting for whoever is responsible if they still active to get their fingers out

**Comment by Stanzilla** [comment]
^ @pragmaware a chance to get that in Git?

**Comment by un1versal** [comment]
Docs done its not on that todo list but its done.

**Comment by un1versal** [comment]
@Stanzilla https://github.com/kvirc/kvirc-www/tree/master/translation its all there.

**Comment by HelLViS69** [comment]
The question that come in mind is: if quite every content of the site links to github, does it make sense to keep the site? IMHO github should just be an help as code repo as it born to do, not a substitute of the site

**Comment by un1versal** [comment]
Site is not going to be replaced, just content updated from the dark ages to reflect what's going on now
much of the general content on website is severely outdated and no longer relevant to anything.

A good example http://www.kvirc.net/?id=snapshots&lang=en

**Comment by HelLViS69** [comment]
Ok, but if "this page" links to github, "that one" links to github, "that other one" links to github.. how many pages will remain on the site? a few?

**Comment by un1versal** [comment]
A few pages will stay I imagine BUT... Well, thats up to who is the website maintainer, but my suggestion is that pages get condensed and pages that are superfluous removed and definitely not duplicate things needlessly.

FAQ and such manuals, we could use the Github wiki and link to actual install docs and instructions instead of just duplicating same information, its also a nightmare to maintain.

I think we all love K.i.s.s. process going forward?

I had a stab at a few minors on https://github.com/kvirc/kvirc-www/pull/9/files and found much that could be in the process of condensing and making website relevant again. 

Thats my contrib here I can make the odd one here and there but working alone on it no!

**Comment by HelLViS69** [comment]
Well, I was the maintainer for some years, and quite almost all stuff/engine that's behind the site was written by me. It's not a problem to continue maintaing the site, I just need to know what's the way to follow (what to keep on the site and what to move on github), but for this we need to hear @pragmaware who has the last word.
Moreover, the site is now quite old and can be ported to HTML5.
About the locale_en.php, you have to reflect those changes also in other languages files.. if you intend to contribute in texts, there's no problem, I'll merge your commits but I suggest to wait editing until we have a clear stub to follow.. this is just to avoid to make you work on texts that maybe will be removed

**Comment by un1versal** [comment]
I do try to speak to pragma to review stuff and we talk about odds and ends but its mostly themes and graphics related. 

Translations, I understand that these things have to be reflected there it was my understanding its up to translators who handle the reflection of these things even program wide. I cant do this myself in anycase, a google translator isnt acceptable imo. :smile: 

If the work I did get lost, It get lost, I wont be heartbroken, I did it to fix mainly the many spelling errors and update the remainder SVN entries and also updated the project status page and put 4.2.0 in there instead of 4.0.4 on https://github.com/kvirc/kvirc-www/commit/c905bb76dfcba8c6efb7cfb6ff58e9b855dae899

Going forward we should put aside some time (you me, pragma and whoever else is active) to discuss these things and other project related things as a team, 
There's plenty todo on my end and these and thats my priority  doing these website minors was a break from my tedious stuff.

We should talk, Im in UK time anywho if that matters.

**Comment by Coldblackice** [comment]
(Redirecting my channel input here)

Just a bit of brainstorming on revamping the main site's UX and design. No complaints -- I don't even use the site anymore -- purely in the interest of attracting a wider userbase. The current look, layout, and design have a very dated feel to it, and I sense it may dissuade some newcomers, particularly more professional types. 

People make snap judgments based on looks of things, for better or worse, and so it behooves anyone looking to "sell" something to put a best look forward, even if it's unrelated to the actual end-product.

I have a lot of experience with good design and user interaction, and would be more than happy to implement any of the below:
- Revamp KVIrc's site with a more modern "web 2.0" look
  - Replace tiny, year-2000'ish looking fonts with more modern font/size (bigger)
  - Change dated 70's-looking color scheme (especially faded yellow)
  - Remove graffiti-style logo text, which may appear to cater to script-kiddie/h4xor types (i.e., may dissuade more mature/professional users)
  - Remove stock-photo image from front page, replace with sexy in-program screenshot(s)
  - Redo the confusing, non-uniform navigation bar/buttons
    - remove dropdown menus (dated, 2000's-ish style), condense into single buttons
    - remove "features" subsection, list features on front page
    - change "the project" button to "About"
    - change "running KVIrc" to "Download"
    - merge "tools" and "scripts" into same page/button, perhaps "Addons"
    - change "honor and glory" --> merge into "About"
- Remove the unnecessary dump of "mirrors" from front page, as it's confusing, If there are users/areas/servers that still have issues accessing the site in this age, we should set up a dynamically-routing domain, removing the need for user-decision. (Or at least move them to a new "Downloads" page/subsection.
- Remove "old site layouts" from the front page -- distracting
- Remove "Welcome" section from front page, replace with features list + a screenshots

**Comment by un1versal** [comment]
All I have to say instead of typing an essay, is use the K.i.s.s principle.
Use good grammar applied to the absolute minimal content and forget buzz words and fancy designs.

Any website has around 7 seconds (or less) to keep any visitor interested and locate the content they are looking for.

**Comment by Coldblackice** [comment]
I broke it down into bullet-points so it wouldn't be so difficult to read.

KISS doesn't mean you can simply abandon design principles because it's simpler than having to do any work keeping it current with the times. If that was the case, the web today would still look like GeoCities. I understand "minimalist", but even minimalist needs to be kept with the times.

Nothing I've suggested is "fancy". Simply, the site currently looks like a script-kiddie's abandonware project from Y2K, given its look of A.) default blogging template + B.) script-kiddie graffiti logo + C.) stock 3D-art from a fresh Maya install.

In 7 seconds, it gives an immediate impression that the site and software are old, outdated, perhaps abandoned, and geared toward aspiring h4x0rs.

If you're aiming for a Craigslist-style look, then by all means, go for it. But at least remove the anachronistic logo-banner, or at the very least cut its graffiti text + wholly unrelated 3D-vis pole-dancer. And sheesh, remove the "Welcome!". That's a step above leaving in "**It works!** _This is the default web page for this server._"

If the intent is merely being content with current userbase numbers -- i.e., as a small, niche IRC client -- then by all means, let the site's design fade like a vintage 70's photo. My suggestions aren't for keeping those who already use it. My professional work in design can attest that would-be users are surely passing on it because the site looks old, abandoned, and even unsafe (them h4x0rs inject their RATs into anything these days).

**Comment by Coldblackice** [comment]
PS - "_Latest release 4.2.0 : Stable (_**_Jul 2012**__)" [Win/Mac]_ + "_Latest release 4.0.4 : Stable (_**_Mar 2011**__)" [Linux]_

That won't help attract newcomers or confidence, either. At least redirect to d00p's builds at kvirc.d00p.de

**Comment by un1versal** [comment]
I didnt mean to imply K.i.s.s. abandoned any design principles, only that keeping it simple is best no matter what design choices are made. Currently its anything but K.i.s.s.

Im not aiming to anything in particular as I dont speak for anyone else on team only for myself.
But we all seem to agree and or can agree the site is outdated.

Also this is opensource so feel free to contribute in improving the project in general.
Ive made some updates to site content but thats all I can do atm.

So do feel free to submit PR's fixing the blatant issues. Or even recoding the site.

**Comment by Coldblackice** [comment]
K. And I agree on the minimalist design. My suggestions were aimed toward refinement of its current state, as I assumed the group may not want to change up the longtime momentum of the site.

Personally, I think d00p's minimalist layout has a great look -- fresh, clean, and yet modern, current. And for the record, I have no ties nor connections with him. Obviously it would need some things added to it, like contact/docs/etc.

But anyway, sounds good. I'll push some ideas to the repo.

**Comment by DarthGandalf** [comment]
> PS - "Latest release 4.2.0 : Stable (Jul 2012)" [Win/Mac] + "Latest release 4.0.4 : Stable (Mar 2011)" [Linux]
> That won't help attract newcomers or confidence, either. At least redirect to d00p's builds at kvirc.d00p.de

Yes, latest release is really so old. There needs to be a new release. @pragmaware ?

**Comment by un1versal** [comment]
I like d00ps site because its K.i.s.s. maybe we can take a page from that.

**Comment by staticfox** [comment]
This somewhat goes for here and the main KVIrc repo but I strongly agree with @DarthGandalf. Our last release was over 3 years ago and people who go to download KVIrc from the website are unaware that we have way newer builds on github. It reflects when people join #kvirc on freenode to report bugs that were fixed years ago. Personally I think we should map out some milestones (https://github.com/kvirc/KVIrc/milestones) so we can track progress on a release goal.

**Comment by un1versal** [comment]
@stanzilla, do you plan on addressing any of these points you raised via PR or something?

New site is going nowhere fast, HelLViS69 is mia, Im sure some help on this part would be very welcome.

**Comment by un1versal** [comment]
@Stanzilla Im about to push an update PR to www, can you check it please and tick the boxes that it addresses there on your main post.

**Comment by un1versal** [comment]
done somemore fixes to finalise what I started, the rest whoever is feeling the itch feel free to have at it.

**Comment by un1versal** [comment]
fixed broken mirrors and have a PR outstanding, thats me done (9 boxes ticked), @Stanzilla can do the rest :tongue:

**Comment by Stanzilla** [comment]
is there a cronjob running that publishes whatever is in the repo or is it pushed manually?

**Comment by un1versal** [comment]
Once its merged takes anywhere between 20 minutes to an hour depending to be live.

**Comment by un1versal** [comment]
since stanzilla is doing suck a great job on the website, maybe we should close this ticket :grinning:

**Comment by Stanzilla** [comment]
pfff, I only said I start collecting stuff that needs to be fixed, not that I will fix it!

**Comment by un1versal** [comment]
doesnt opensource rock? love it... I love especially how others are so generous with time and skills that isnt their time or their skills :laughing: :lollipop:

**Comment by un1versal** [comment]
with some luck https://github.com/kvirc/kvirc-www/issues/20 will come to fruition and this is a no go anymore. closing here
